In [50]:
import numpy as np 
import pandas as pd 
import tensorflow as tf 

In [51]:
data=pd.read_excel("Folds5x2_pp.xlsx")

In [52]:
data

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [53]:
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [54]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [55]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [56]:
from sklearn.model_selection import train_test_split

In [57]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [58]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(7654, 4)
(1914, 4)
(7654,)
(1914,)


In [59]:
from sklearn.preprocessing import StandardScaler 

In [60]:
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [61]:
print(X_train)

[[-1.75 -1.21  0.42  1.3 ]
 [ 0.41  0.89  0.23 -0.19]
 [-1.29 -1.16  0.83 -0.22]
 ...
 [-0.14 -1.16 -0.78 -0.33]
 [ 0.45 -0.73 -0.17 -1.55]
 [ 0.12 -0.36 -0.61 -0.18]]


In [62]:
print(X_test)

[[-0.23 -0.76 -1.62  0.97]
 [-0.44 -0.95 -0.86 -1.41]
 [ 0.85  1.26 -0.96 -1.12]
 ...
 [-1.21 -1.25  1.26 -0.07]
 [ 1.94  1.51 -1.13 -1.53]
 [-0.59 -0.77  0.53  0.67]]


In [63]:
# instance for ANN 
ann= tf.keras.models.Sequential()

In [64]:
# layers -> dense is used 
ann.add(tf.keras.layers.Dense(units = 6 , activation = 'relu'))
# units - > no of neurons in layer 
# activation -> activation function used 

In [65]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [66]:
# OUTPUT layer 
ann.add(tf.keras.layers.Dense(units = 1))

In [67]:
# TILL HERE ANN is created only 

In [68]:
# the ANN is configured together 
# specific setting to implement 
ann.compile(optimizer='adam',loss='mean_squared_error')

In [69]:
ann.fit(X_train,y_train, batch_size=32, epochs = 200)

Epoch 1/200
240/240 [==============================] - 2s 3ms/step - loss: 204177.8281
Epoch 2/200
240/240 [==============================] - 1s 3ms/step - loss: 186362.0312
Epoch 3/200
240/240 [==============================] - 1s 4ms/step - loss: 132921.6094
Epoch 4/200
240/240 [==============================] - 1s 3ms/step - loss: 66546.8984
Epoch 5/200
240/240 [==============================] - 1s 3ms/step - loss: 30636.4707
Epoch 6/200
240/240 [==============================] - 1s 3ms/step - loss: 19053.0645
Epoch 7/200
240/240 [==============================] - 1s 3ms/step - loss: 14183.3779
Epoch 8/200
240/240 [==============================] - 1s 3ms/step - loss: 10634.5000
Epoch 9/200
240/240 [==============================] - 1s 3ms/step - loss: 7630.5845
Epoch 10/200
240/240 [==============================] - 1s 4ms/step - loss: 5168.5786
Epoch 11/200
240/240 [==============================] - 1s 3ms/step - loss: 3308.3379
Epoch 12/200
240/240 [==============================

240/240 [==============================] - 1s 2ms/step - loss: 21.3919
Epoch 99/200
240/240 [==============================] - 1s 2ms/step - loss: 21.2540
Epoch 100/200
240/240 [==============================] - 1s 2ms/step - loss: 21.4267
Epoch 101/200
240/240 [==============================] - 1s 3ms/step - loss: 21.3446
Epoch 102/200
240/240 [==============================] - 1s 3ms/step - loss: 21.3561
Epoch 103/200
240/240 [==============================] - 1s 3ms/step - loss: 21.2435
Epoch 104/200
240/240 [==============================] - 1s 3ms/step - loss: 21.2910
Epoch 105/200
240/240 [==============================] - 1s 3ms/step - loss: 21.3330
Epoch 106/200
240/240 [==============================] - 1s 2ms/step - loss: 21.2099
Epoch 107/200
240/240 [==============================] - 1s 3ms/step - loss: 21.4458
Epoch 108/200
240/240 [==============================] - 1s 3ms/step - loss: 21.5159
Epoch 109/200
240/240 [==============================] - 1s 3ms/step - loss: 21.

240/240 [==============================] - 1s 3ms/step - loss: 21.4010
Epoch 195/200
240/240 [==============================] - 1s 3ms/step - loss: 21.2627
Epoch 196/200
240/240 [==============================] - 1s 2ms/step - loss: 21.2838
Epoch 197/200
240/240 [==============================] - 1s 3ms/step - loss: 21.2743
Epoch 198/200
240/240 [==============================] - 1s 3ms/step - loss: 21.2410
Epoch 199/200
240/240 [==============================] - 1s 3ms/step - loss: 21.3250
Epoch 200/200
240/240 [==============================] - 1s 2ms/step - loss: 21.2848


In [70]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 3ms/step
[[457.   458.96]
 [465.92 463.29]
 [439.17 435.27]
 ...
 [476.79 476.22]
 [422.9  440.29]
 [464.17 467.92]]


In [71]:
from sklearn.metrics import r2_score

In [72]:
r2_score(y_test, y_pred)

0.9313365696406274