In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = pd.read_csv("diabetes.csv")

In [3]:
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [6]:
X=data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [7]:
print(X.shape)
print(y.shape)

(768, 8)
(768,)


# Splitting dataset 

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [9]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(614, 8)
(154, 8)
(614,)
(154,)


# Scaling the dataset 

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
print(X_train)

[[ 0.90832902  0.91569367  0.44912368 ...  0.37852648  0.67740401
   1.69955804]
 [ 0.03644676 -0.75182191 -0.47230103 ... -0.50667229 -0.07049698
  -0.96569189]
 [-1.12606292  1.38763205  1.06340683 ...  2.54094063 -0.11855487
  -0.88240283]
 ...
 [ 0.03644676 -0.84620959 -0.21634972 ... -0.94927168 -0.95656442
  -1.04898095]
 [ 2.0708387  -1.12937261  0.24436264 ... -0.26640405 -0.50001442
   0.11706589]
 [ 0.32707418  0.47521786  0.65388473 ... -4.07275877  0.52121586
   2.94889395]]


In [13]:
print(X_test)

[[-0.8354355   2.45735903  0.34674316 ...  1.35224513  2.78594417
  -0.96569189]
 [-0.54480808 -0.43719633  0.24436264 ...  0.17619533 -0.1876381
  -0.88240283]
 [ 0.03644676 -1.41253563 -0.36992051 ...  0.22677812 -0.22668514
  -0.71582471]
 ...
 [ 0.03644676  0.66399321  0.85864578 ...  1.4913478   0.53623395
  -0.96569189]
 [-0.25418066 -0.15403331  0.24436264 ... -0.74694053 -1.07971278
  -0.79911377]
 [-0.8354355  -0.43719633  0.14198211 ... -0.17788417  1.06487079
  -0.79911377]]


# Logistic Regression 

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
model_lr = LogisticRegression(random_state=0)
model_lr.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [16]:
y_pred_lr = model_lr.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [18]:
cm = confusion_matrix(y_test,y_pred_lr)
print(cm)
accuracy_score(y_test,y_pred_lr)

[[98  9]
 [18 29]]


0.8246753246753247

# SVC

In [19]:
from sklearn.svm import SVC

In [20]:
model_svc = SVC(kernel="linear", random_state=0)
model_svc.fit(X_train,y_train)

SVC(kernel='linear', random_state=0)

In [21]:
y_pred_svc = model_svc.predict(X_test)

In [22]:
cm = confusion_matrix(y_test,y_pred_svc)
print(cm)
accuracy_score(y_test,y_pred_svc)

[[98  9]
 [18 29]]


0.8246753246753247

# Kernel SVC 

In [24]:
model_kernel = SVC(kernel='rbf',random_state=0)
model_kernel.fit(X_train,y_train)

SVC(random_state=0)

In [25]:
y_pred_kernel_svc = model_svc.predict(X_test)

In [26]:
cm = confusion_matrix(y_test,y_pred_svc)
print(cm)
accuracy_score(y_test,y_pred_svc)

[[98  9]
 [18 29]]


0.8246753246753247

# KNN 

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
model_knn = KNeighborsClassifier(p=2,metric='minkowski',n_neighbors=5)
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [29]:
y_pred_knn = model_knn.predict(X_test)

In [30]:
cm = confusion_matrix(y_test,y_pred_knn)
print(cm)
accuracy_score(y_test,y_pred_knn)

[[93 14]
 [17 30]]


0.7987012987012987

# Naive Bayes 

In [31]:
from sklearn.naive_bayes import GaussianNB

In [32]:
model_naive = GaussianNB()
model_naive.fit(X_train,y_train)

GaussianNB()

In [33]:
y_pred_naive = model_naive.predict(X_test)

In [34]:
cm = confusion_matrix(y_test,y_pred_knn)
print(cm)
accuracy_score(y_test,y_pred_knn)

[[93 14]
 [17 30]]


0.7987012987012987

# Decision Tree 

In [35]:
from sklearn.tree import DecisionTreeClassifier

In [36]:
model_tree = DecisionTreeClassifier(criterion="entropy",random_state=0)
model_tree.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [37]:
y_pred_tree = model_tree.predict(X_test)

In [38]:
cm = confusion_matrix(y_test,y_pred_knn)
print(cm)
accuracy_score(y_test,y_pred_knn)

[[93 14]
 [17 30]]


0.7987012987012987

# Randomforest

In [42]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
model_rf.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [43]:
y_pred_rf = model_rf.predict(X_test)

In [44]:
cm = confusion_matrix(y_test,y_pred_knn)
print(cm)
accuracy_score(y_test,y_pred_knn)

[[93 14]
 [17 30]]


0.7987012987012987

# In above models Kernel SVC showed the best accuracy

# Applying k-fold 

In [45]:
from sklearn.model_selection import cross_val_score 

In [46]:
accuracies = cross_val_score(estimator=model_kernel, X=X_train, y=y_train, cv=10)
print("Accuracy = {:.2f} %".format(accuracies.mean()*100))
print("standard deviation = {:.2f} %".format(accuracies.std()*100))

Accuracy = 74.92 %
standard deviation = 3.70 %


# Grid search 

In [48]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid = GridSearchCV(estimator = model_kernel,
                   param_grid = parameters,
                   scoring="accuracy",          # metric 
                   cv=10,                 # no of bins 
                   n_jobs = -1            # no of processors 
                   )
grid.fit(X_train,y_train)
best_accuracy = grid.best_score_
best_parameter = grid.best_params_
print("best accuracy = {:.2f} %".format(best_accuracy*100))
print("best parameter = ",best_parameter)


best accuracy = 76.39 %
best parameter =  {'C': 0.25, 'gamma': 0.1, 'kernel': 'rbf'}
